name: Despliegue a Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Hacer checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar surge
        run: npm install --global surge

      - name: Verificar archivos del proyecto
        run: ls -R

      - name: Desplegar a Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          surge --project ./ --domain mi-pagina-web1.surge.sh --token $SURGE_TOKEN --force
